name: LintersAndCheckers

on:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: install checkers
      run: |
        pip install black flake8 'black[jupyter]' isort mypy types-PyYAML
    - name: black
      run: black . --check --diff
    - name: flake8
      run: flake8 .
    - name: isort
      run: isort . --check --diff
    - name: mypy
      run: mypy .
